INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 1", "commerce", 30000, "January 1, 2016", "April 20, 2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 2", "film", 50000, "January 12, 2016", "April 29, 2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 3", "art", 10000, "February 12, 2016", "August 10, 2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 4", "commerce", 100000, "January 31, 2016", "January 20, 2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 5", "theater", 25000, "January 1, 2016", "April 20, 2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 6", "film", 60000, "July 11, 2016", "September 20, 2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 7", "journalism", 7000, "March 15, 2016", "October 12, 2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 8", "art", 1500, "July 21, 2016", "August 21, 2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 9", "commerce", 22000, "January 13, 2016", "April 23, 2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 10", "game", 40000, "May 1, 2016", "November 20, 2016");

INSERT INTO users (name, age) VALUES ("Matthew", 30);
INSERT INTO users (name, age) VALUES ("Mark", 22);
INSERT INTO users (name, age) VALUES ("Luke", 55);
INSERT INTO users (name, age) VALUES ("John", 72);
INSERT INTO users (name, age) VALUES ("Abel", 33);
INSERT INTO users (name, age) VALUES ("Cain", 45);
INSERT INTO users (name, age) VALUES ("Lazarus", 42);
INSERT INTO users (name, age) VALUES ("Mary", 24);
INSERT INTO users (name, age) VALUES ("Rebecca", 62);
INSERT INTO users (name, age) VALUES ("Isaac", 15);
INSERT INTO users (name, age) VALUES ("Abraham", 92);
INSERT INTO users (name, age) VALUES ("Gurion", 26);
INSERT INTO users (name, age) VALUES ("Ben", 60);
INSERT INTO users (name, age) VALUES ("Paul", 33);
INSERT INTO users (name, age) VALUES ("Fredrich", 46);
INSERT INTO users (name, age) VALUES ("Adam", 34);
INSERT INTO users (name, age) VALUES ("Eve", 32);
INSERT INTO users (name, age) VALUES ("Stuart", 58);
INSERT INTO users (name, age) VALUES ("Craig", 27);
INSERT INTO users (name, age) VALUES ("Lawrence", 39);

INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 17, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 17, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 16, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 17, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 14, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 8, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 8, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 14, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 3, 7);
